### ISSUE TITLE
bfp inverse + multiply precision issue

### ISSUE THREAD

**Issue by uvvpavel** [xmos/lib_xs3_math#89] opened 2022-03-15 15:57 UTC
After testing bfp_s32_inverse + bfp_s32_multiply combination, I've noticed that the output of some output bfps have large headroom (max I've seen was 10). I've generated small arrays to showcase this issue. They can be found here:
https://xmosjira.atlassian.net/wiki/spaces/~94391093/pages/3387883533/lib+xs3+math+presicion+issue

**Comment by astewart-xmos** [comment] 2022-04-20 19:51
I was able to reproduce the result shown on that Jira page.  As best I can tell, everything is working correctly.

Here's what I see happening (I'm assuming other cases where you've seen this end up following similar logic):

The result of `bfp_s32_inverse(a, a)` is fine. `a` (now holding the inverse) has only 1 bit of headroom. The scale (and thus headroom) of the output of `bfp_s32_inverse()` will be determined by the element with the _smallest magnitude_, as this will become the largest (magnitude) element of the inverse.  In this case, that element is `a.data[6]`, which has value `3108726` (`0x2f6f76').

After inversion, `a.data[6]` has the value `724348113` (`0x2b2cacd1`), which has a headroom of `1` (because there is 1 _redundant_ leading sign bit).

Meanwhile, the headroom of `b` is also determined by the largest element, which in this case is `b.data[8] = 2017004453` (`0x78390ba5`).

So, when `bfp_s32_mul()` happens, one operand has 1 bit of headroom, and the other has 0.  Because of that, this seems like an ideal case for `bfp_s32_mul()`.

---

The first fundamental issue:  **the element which dictates the headroom of inverse `a` isn't at the same index as the element which dictates the headroom of `b`.**

The block floating-point multiplication doesn't know _which_ elements in the operands are the largest, only how many redundant sign bits the largest element has.  To avoid saturation or overflows, the multiply function has to account for the worst possible case, given the data it has. That ultimately means it has to assume that the largest element of each operand are _at the same index_.

When that assumption gets violated, the result is more headroom than strictly necessary.  Unfortunately, there's no way to detect this prior to the multiplication without iterating over every element of each array, comparing redundant sign bits on an element-by-element basis (which of course loses nearly all the benefits of BFP and the VPU).

---

The second fundamental issue:  **the VPU _always_ right-shifts the product of 32-bit multiplies by 30 bits.**

Consider the following two 32-bit vectors. The exponents are unimportant.

```c
a_vec[] = {-0x40000000, 0x00100000 };
b_vec[] = { 0x00100000, -0x40000000 };
```

The headroom of each vector is 1 bit. In `a_vec[]` it's determined by the first element. In `b_vec[]` it's determined by the second element.

What's the best thing we can do here? We can remove the headroom from each vector and multiply:

```c
a_vec_shifted[] = {-0x80000000, 0x00200000 };
b_vec_shifted[] = {0x00200000, -0x80000000 };
```

Here, each multiplication (`-(2**31) * 2**21`) has an intermediate 64-bit product of: `-0x0010000000000000 = -(2**52)`.

The hardware then applies a 30-bit right-shift to get `-(2**(52-30)) = -(2**22) = -0x00400000` which has a full 9 bits of headroom. There's nothing we can do about that using the VPU, because we've already gotten rid of all the headroom we could before multiplying.

Consider now, if each vector had a third element, `0x10000000`, with bits of headroom. The `-0x40000000`s still determine the headroom, so we still shift by one bit so that we're multiplying `0x20000000 * 0x20000000 = 2**29 * 2**29 = 2**58`. That gets shifted down 30 bits, as usual, to `2**28 = 0x10000000`.  Now the output vector only has 2 bits of headroom instead of 9, even though the headroom of the input vectors and the shifts we applied didn't change.

---

Unfortunately, I can't offer you much here.  One possibility is that you could perform a modified version of [`bfp_s32_mul()`](https://github.com/xmos/lib_xs3_math/blob/develop/lib_xs3_math/src/bfp/bfp_s32.c#L120-L135) which does the ordinary `xs3_vect_s32_mul()`, but then, if there's at least 1 bit of headroom in the result, you could perform `xs3_vect_s32_mul()` _a second time_. 

This second time use `b_shr = -(b->hr)` and `c_shr=-(c->hr)`, where `a->exp` will be `b->exp + c->exp + b_shr + c_shr + 30`.

This should still be faster than the work-around mentioned on Jira, but it probably won't gain you more than 1 or maybe 2 bits of precision (because the `b_shr` and `c_shr` computed by `xs3_vect_s32_mul_prepare()` are unlikely to have been more than 1 larger than the new values).

**Comment by astewart-xmos** [comment] 2022-04-20 20:03
If the MIPS cost of your work-around is a serious issue for the DSP, we can dig in deeper to see if either: 
* we can tweak the surrounding logic to mitigate the issue, or 
* maybe we can trick the VPU in some round-about way into doing some seriously sketchy dark magic.

**Comment by astewart-xmos** [comment] 2022-04-21 14:37
I spoke to Pavel and made a couple of suggestions that might help.  I'll include them here in case anyone stumbles across this issue in the future with a similar problems.  

Both are based on the observation that often frequency domain vectors have a large dynamic range where the low-frequency components are much larger than the high-frequency components.  In these situations, the low-frequency components will tend to constrain the number of bits available to high-frequency components, since it is the largest component that determines a vector's exponent.

---

**Break up large BFP vectors into multiple smaller BFP vectors and operate on each of those separately.** 

This allows the low- and high-frequency components to have different exponents, so that their precision isn't dictated by the low-frequency components.  Eventually they'll need to be recombined, which is achieved by forcing all sub-vectors back to the same exponent. 

Once recombined, the low-frequency components will again (probably) dominate the precision of high-frequency components, but the point is that it avoids precision issues in the _intermediate results_.  (Don't forget to recompute headroom of the full vector once everything has been recombined!).

---

**Apply a frequency-dependent weighting.**  

More care has to be taken with this approach (though it avoids any potential sub-vector boundary oddities that the previous approach might have).  Suppose you find, for example, that the magnitude of vector components are roughly inversely proportional to their frequency. The idea here is that you may then be able to scale up vector components in a way that is linear-ish in frequency to bring all components to roughly the same scale. This way, high-frequency components have less headroom and are thus able to retain more precision in intermediate results. 

More care has to be taken here because you have to be cognizant of the effect that the scaling will have on intermediate results. If all operations are element-wise and linear, then at the end of the process, you can scale everything back down by the inverse of the input scale, and you should get back approximately the same as before (though hopefully with fewer quantization errors.)  

Even if all operations are linear, if they're not also element-wise, the effect of the scaling needs to be considered carefully. For example, if a vector scaled in this way is used as an input to a dot product, the scaling needs to be inverted first, or else the weighting will bleed into the result in a way that can't be undone.

Likewise, element-wise non-linear operations suffer similar problems. If you have to square the elements of the vector, then the result will be weighted by the _squares_ of the original weight curve.

---

With Pavel's consent I'm closing this issue, as there's no obvious change to be made to the library code for this.  I have, however, opened a new issue (#94) to add some discussion/advice on cases like these to the library's documentation.

**Closed by astewart-xmos** 2022-04-21 14:37 UTC
Labels: type:bug
